console.log(process.env)

/**
 {
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\Lenovo\\AppData\\Roaming',
  COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'DESKTOP-RI7J3IM',
  COMSPEC: 'C:\\Windows\\system32\\cmd.exe',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  EXEPATH: 'C:\\software\\Git\\bin',
  FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
  FPS_BROWSER_USER_PROFILE_STRING: 'Default',
  HOME: 'C:\\Users\\Lenovo',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\Lenovo',
  IDEA_INITIAL_DIRECTORY: 'C:\\Users\\Lenovo\\Desktop',
  INIT_CWD: 'E:\\my_project\\scripts-demo\\params',
  'IntelliJ IDEA': 'C:\\software\\IntelliJ IDEA 2022.2.1\\bin;',
  JAVA_HOME: 'C:\\software\\jdk',
  LOCALAPPDATA: 'C:\\Users\\Lenovo\\AppData\\Local',
  LOGONSERVER: '\\\\DESKTOP-RI7J3IM',
  MAVEN_HOME: 'E:\\cache\\java_maven\\apache-maven-3.8.1\\apache-maven-3.8.1',
  MSYSTEM: 'MINGW64',
  NODE: 'C:\\software\\nodejs\\node.exe',
  npm_config_argv: '{"remain":[],"cooked":["run","print"],"original":["print"]}',
  npm_config_bin_links: 'true',
  npm_config_home: 'https://npm.taobao.org',
  npm_config_ignore_optional: '',
  npm_config_ignore_scripts: '',
  npm_config_init_license: 'MIT',
  npm_config_init_version: '1.0.0',
  npm_config_registry: 'https://registry.yarnpkg.com',
  npm_config_save_prefix: '^',
  npm_config_strict_ssl: 'true',
  npm_config_user_agent: 'yarn/1.22.19 npm/? node/v16.17.0 win32 x64',
  npm_config_version_commit_hooks: 'true',
  npm_config_version_git_message: 'v%s',
  npm_config_version_git_sign: '',
  npm_config_version_git_tag: 'true',
  npm_config_version_tag_prefix: 'v',
  npm_execpath: 'C:\\software\\nvm\\v16.17.0\\node_modules\\yarn\\bin\\yarn.js',
  npm_lifecycle_event: 'print',
  npm_lifecycle_script: 'node params/run.js',
  npm_node_execpath: 'C:\\software\\nodejs\\node.exe',
  npm_package_description: '',
  npm_package_devDependencies__types_node: '^18.7.19',
  npm_package_license: 'ISC',
  npm_package_main: 'index.js',
  npm_package_name: 'scripts-demo',
  npm_package_scripts_build: 'node npm-hooks/build.js',
  npm_package_scripts_postbuild: 'node npm-hooks/postbuild.js',
  npm_package_scripts_prebuild: 'node npm-hooks/prebuild.js',
  npm_package_scripts_print: 'node params/run.js',
  npm_package_version: '1.0.0',
  NUMBER_OF_PROCESSORS: '8',
  NVM_HOME: 'C:\\software\\nvm',
  NVM_SYMLINK: 'C:\\software\\nodejs',
  OLDPWD: 'E:/my_project/scripts-demo',
  OneDrive: 'C:\\Users\\Lenovo\\OneDrive',
  OS: 'Windows_NT',
  PATH: 'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\yarn--1664008710318-0.13488875945057877;E:\\my_project\\scripts-demo\\node_modules\\.bin;C:\\Users\\Len
ovo\\AppData\\Local\\Yarn\\Data\\link\\node_modules\\.bin;C:\\Users\\Lenovo\\AppData\\Local\\Yarn\\bin;C:\\software\\libexec\\lib\\node_modules\\npm\\bin
\\node-gyp-bin;C:\\software\\lib\\node_modules\\npm\\bin\\node-gyp-bin;C:\\software\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin;C:\\software\\Git\\ming
w64\\bin;C:\\software\\Git\\usr\\bin;C:\\Users\\Lenovo\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System
32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\software\\Git\\cmd;C:\\software\\jdk\\bin;C:\\software\\nvm;C:
\\software\\nodejs;E:\\cache\\java_maven\\apache-maven-3.8.1\\apache-maven-3.8.1\\bin;C:\\software\\xshell;C:\\software\\xfpt;C:\\Users\\Lenovo\\AppData\
\Local\\Microsoft\\WindowsApps;C:\\software\\WebStorm 2022.2.1\\bin;C:\\software\\IntelliJ IDEA 2022.2.1\\bin;C:\\software\\nvm;C:\\software\\nodejs;C:\\
software\\Microsoft VS Code\\bin',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
  PLINK_PROTOCOL: 'ssh',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '8c01',
  ProgramData: 'C:\\ProgramData',
  PROGRAMFILES: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PROMPT: '$P$G',
  PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
  PUBLIC: 'C:\\Users\\Public',
  PWD: 'E:/my_project/scripts-demo/params',
  SESSIONNAME: 'Console',
  SHLVL: '1',
  SYSTEMDRIVE: 'C:',
  SYSTEMROOT: 'C:\\Windows',
  TEMP: 'C:\\Users\\Lenovo\\AppData\\Local\\Temp',
  TERM: 'xterm-256color',
  TERMINAL_EMULATOR: 'JetBrains-JediTerm',
  TERM_SESSION_ID: 'a2eeafa1-1294-4727-88f2-aa4a84d6dfc1',
  TMP: 'C:\\Users\\Lenovo\\AppData\\Local\\Temp',
  USERDOMAIN: 'DESKTOP-RI7J3IM',
  USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-RI7J3IM',
  USERNAME: 'Lenovo',
  USERPROFILE: 'C:\\Users\\Lenovo',
  WebStorm: 'C:\\software\\WebStorm 2022.2.1\\bin;',
  WINDIR: 'C:\\Windows',
  YARN_WRAP_OUTPUT: 'false',
  ZES_ENABLE_SYSMAN: '1',
  __INTELLIJ_COMMAND_HISTFILE__: 'C:\\Users\\Lenovo\\AppData\\Local\\JetBrains\\WebStorm2022.2\\terminal\\history\\scripts-demo-history'
}
 */